### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by blacksector**
Closing tag missing

### CODE REVIEW

**Comment by nawazdhandala** [comment]
haha. You're a rockstar. Thank you! :)

**Comment by blacksector** [comment]
No worries! I hope to make some contributions that are a bit more meaningful soon. if you guys need help with that whole local storage thing, I think I can help out if you guys arent already done that is! :)

**Comment by nawazdhandala** [comment]
Sure. We're not on that yet. You can give it a shot. :)

**Comment by blacksector** [comment]
I'll give it a shot in a few days time hopefully For now i'll just clone the project and possibly add some stuff here or there.

**Comment by nawazdhandala** [comment]
I'll be on that for now because I'm guessing devs need that ASAP. :) but you can add your contributions here or there and I can accept your PR's. We were using Jenkins internally for CI, I'm moving this to Travis. So, you should be able to check if your build passes or fails.

**Comment by blacksector** [comment]
I normally dont work with building platforms, I just do it, test it and done! haha I guess i should get used to those now though, as that is now becoming the standard. But alright great, i'll add contributions in other ways.

**Comment by nawazdhandala** [comment]
haha. I was like you until few years ago and then realized its actually important because the new code you write usually breaks another set of code. CI makes sure that never happens.

**Comment by blacksector** [comment]
Haha first i guess i must figure out how it works then get onto using it :) Thanks anyway! I am going to get started on Travis and slowly try to understand it in the next few weeks

**Comment by nawazdhandala** [comment]
Sure! Let me know if you need any help.

**Comment by blacksector** [comment]
Will do! Thank you :)

**Pull request merged**
